version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "50051:50051"
    environment:
      - JWT_SECRET=supersecret
    networks:
      - app-network

  user-service:
    build: ./user-service
    depends_on:
      - auth-service
    environment:
      - AUTH_SERVICE_URL=auth-service:50051
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
